language: java
jdk:
- oraclejdk-ea
- oraclejdk10
- oraclejdk9
- oraclejdk8
- openjdk11
- openjdk10
- openjdk9
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  secure: n8w9Q3017f/iLwKVIBdneUmnk/GsRr/kszgaJEaMIJkMaOVKUWbPOIIGFzi4DvUowN3c93AMvaB2+K7taabPkd+KSUTeK6zg4Wxp1+V9W+4E37RjTvDDG8Tyx5MH2I20TPl9hR5nh+5AyADbMRRbn2XL7F2yMqacjTqK7W/4sDBT97ELRRy6JZMYWBRqfdNSSLy1I/QsQBP9j0ymSgrcbukMIvNQv/2zD67vrLMlMf6U/bsjQQ/s5+oi9aMnsG9O34+OCOjLxiFr6vK28ylfipnNW4Q+uK3ItYsnldolgF/kz4USjS794BugcjtqErPleGOOofRFwV+xEIQ1UsU1ID0E7Dm0Wk99tniwYW/2fxvPL5rc+fmF1sx+8o182n6vJIAAYRN/VPkew+1tZCpK9NauI6VGBUabltqTvj1soqZOg3b2zUI/VaVOLi9Cx45kMrJIVubJKHJLjrbrn9lEGWQ8W2+5lnARmBFwZ/eSfo0mYtMQE+zUR8R+zFcH/3otlL0288P3MjTJ2+XZ5FMMrR1SZ7q2x9xKfbBS1M+7u4ctHW3b/Dz6nxR7rJYEhxcNQbAlurKC6mUO4uBtdpy/UfMVUvafnJXlVb7RwneKw8GFIBZwz16SEHs+TSFmgJ9Av/bSD0e0Hh90/EyR+/XVT3+6O4DTYlavz5DkBmhYGY0=
script:
- "gradle wrapper --gradle-version 4.8"
- "./gradlew assemble -x test --parallel --configure-on-demand"
- "./gradlew test --info"
- "./gradlew jacocoTestReport"
- bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
